// ============================================================================
// MODULE 2, EXERCISE 2: Student Domain Model
// ============================================================================
//
// File Organization: One file per domain concept (Angular best practice)
// This mirrors the C# backend Student class and enforces type safety on the
// frontend. Every response from GET /api/students/{id} must match this shape.
//
// Key Concepts Demonstrated:
// 1. READONLY properties: readonly id cannot be reassigned after initialization
// 2. OPTIONAL properties: gpa? means the property may be undefined
// 3. STRUCTURAL TYPING: If an object has the right shape, it satisfies the
//    interface automatically. The name doesn't matter - the shape is the model.
//
// ============================================================================

import { Temporal } from "@js-temporal/polyfill";

// ============================================================================
// EXERCISE 2: TMS Domain Models - Student Interface
// ============================================================================
//
// Situation: The C# backend defines Student you built this in M1. The frontend
// needs a matching TypeScript interface so API responses have a known shape.
// If the backend returns { id: string, grade: number } and the frontend expects
// { id: number, grade: string }, the app silently breaks at runtime.
//
// In C#, a class must explicitly declare class Quiz : IGradable (nominal typing).
// TypeScript uses STRUCTURAL TYPING: if an object has the right shape (the right
// properties with the right types), it satisfies the interface automatically.
// The name doesn't matter - the shape is the model.
//
// Decision Rule:
// - Use readonly on ID fields and any property that should not change after
//   creation. In C#, readonly is enforced by the CLR at runtime. In TypeScript,
//   it is compile-time only - the JavaScript output has no concept of it.
//   The value is in catching mistakes during development.
// - Use ? for optional properties. gpa?: number means the property may be
//   undefined. With strictNullChecks enabled, the compiler forces you to handle
//   the missing case.
//
// Trade-off: TypeScript's readonly vanishes in the compiled JavaScript. If
// someone modifies the object using raw JavaScript, the protection is gone.
// This is expected - TypeScript guarantees only apply within the TypeScript
// codebase.
//
// ============================================================================

/**
 * STUDENT INTERFACE
 *
 * Purpose: Represents a student enrolled in the TMS system.
 * This interface defines the structure of Student data that flows from the
 * backend API to the TypeScript frontend.
 *
 * API Endpoint: GET /api/students/{id}
 * Example Response:
 * {
 *   "id": "STU-001",
 *   "name": "Hana Tadesse",
 *   "enrollmentDate": "2024-01-15T10:30:00Z",
 *   "gpa": 3.85
 * }
 *
 * TypeScript vs C# Comparison:
 * C# Student class has readonly StudentId (CLR enforced)
 * TypeScript Student interface has readonly id (compile-time only)
 *
 * Usage:
 * - API responses: GET /api/students/{id}
 * - Service layer: StudentService returns Student[]
 * - Components: Display student information in UI
 * - Type guards: Validate unknown API data with isStudent()
 */
export interface Student {
  /**
   * PROPERTY: id (readonly)
   *
   * Purpose: Unique identifier for the student
   * Type: string (non-nullable)
   * Format: "STU-XXXXX" (e.g., "STU-00123")
   * Constraint: readonly - cannot be changed after initialization
   *
   * Why readonly?
   * Student IDs are generated by the backend and should never change.
   * Making it readonly prevents accidental reassignment:
   *   student.id = "STU-999"; // Error: Cannot assign to readonly property
   *
   * Compile-time Safety Only:
   * readonly is a TypeScript concept and is erased in the JavaScript output.
   * If someone accesses the object via raw JavaScript, the protection is gone.
   * This is expected - TypeScript guarantees only apply within TypeScript code.
   *
   * Used as: Primary key, API identifier, uniqueness constraint
   */
  readonly id: string;

  /**
   * PROPERTY: name
   *
   * Purpose: Human-readable name of the student
   * Type: string (non-nullable)
   * Constraint: Mutable - can be updated if legal name changes
   * Length: 1-200 characters
   *
   * Why not readonly?
   * Student names may legitimately change (marriage, legal name change).
   * The name property is mutable but still type-safe.
   *
   * Validation: Should be trimmed on backend before sending to frontend
   * Example: "Hana Tadesse"
   *
   * Frontend Usage:
   * - Display in student profile
   * - Show in grade roster
   * - Search queries ("Find student named...")
   */
  name: string;

  /**
   * PROPERTY: enrollmentDate
   *
   * Purpose: When the student enrolled in the TMS system
   * Type: Temporal.Instant (non-nullable, timezone-aware, UTC)
   * Constraint: Set once during enrollment, never changes
   * Format: ISO 8601 (e.g., "2024-01-15T10:30:00Z")
   *
   * Why Temporal.Instant?
   * JavaScript's legacy Date object is timezone-naive and has many bugs.
   * Temporal.Instant provides:
   * - Precise timezone-aware datetime handling
   * - Arithmetic operations (add days, compare dates, etc.)
   * - No DST bugs or Y2K issues
   *
   * Backend Equivalence: C# DateTime (UTC)
   *
   * Used for:
   * - Academic year calculation
   * - Tenure computation ("When did this student start?")
   * - Enrollment audit trail
   *
   * Example Usage:
   * const daysEnrolled = Temporal.Now.instant().since(student.enrollmentDate);
   */
  enrollmentDate: Temporal.Instant;

  /**
   * PROPERTY: gpa (OPTIONAL)
   *
   * Purpose: Current GPA for the student
   * Type: number | undefined (nullable - IMPORTANT)
   * Range: 0.0 to 4.0 when present
   * Default: undefined (not calculated until first grade)
   * Precision: Two decimal places (e.g., 3.85)
   *
   * Why optional (gpa?)?
   * New students have no GPA until they receive their first grade.
   * Using gpa?: number forces the code to explicitly handle the "no grades yet"
   * case using safe navigation (?.) or null coalescing (??).
   *
   * With strictNullChecks enabled:
   *   // FORBIDDEN: Assumes GPA exists
   *   const display = student.gpa.toFixed(2); // Error: gpa might be undefined
   *
   *   // REQUIRED: Handle the undefined case
   *   const display = student.gpa?.toFixed(2) ?? "Not yet graded"; // OK
   *
   * Safe Navigation Operator (?.):
   * - gpa?.toFixed(2) returns undefined if gpa is undefined
   * - Otherwise calls toFixed(2) and returns the result
   *
   * Null Coalescing Operator (??):
   * - If left side is undefined, uses right side instead
   * - "3.85" ?? "Not yet graded" => "3.85"
   * - undefined ?? "Not yet graded" => "Not yet graded"
   *
   * Frontend Usage:
   * - Display in student profile: student.gpa?.toFixed(2) ?? "Not graded"
   * - Sort by GPA (requires null checks)
   * - Color-code based on GPA range
   *
   * Update Frequency:
   * - Recalculated after each grade entry
   * - Sent in GET /api/students/{id} response
   * - May be updated via PATCH /api/students/{id}/gpa
   */
  gpa?: number;
}

// ============================================================================
// EXERCISE 3: Type Guards and Safe API Parsing
// ============================================================================
//
// Situation: The TMS API returns JSON. JSON has no type information - response.json()
// gives you unknown. The legacy code cast everything to any, which allowed invalid
// data to silently corrupt the grade dashboard.
//
// Legacy Dangerous Code:
// function processStudent(data: any) {
//   console.log(`GPA: ${data.gpa.toFixed(2)}`); // Crashes if gpa missing/not number
// }
//
// In M1 C#, you used guard clauses (if (student is null) throw ...).
// TypeScript's type guards serve the same purpose: they prove to the compiler
// that a value has the shape you expect before you use it.
//
// Decision Rule:
// - Use unknown for any data from outside your application (API responses, CSV
//   imports, localStorage, URL parameters). Never use any.
// - Write a type guard (value is Student) when you need the compiler to narrow
//   the type after the check. Use parseStudent (throw on failure) when invalid
//   data should stop execution.
//
// Trade-off: Type guards return boolean - the caller decides what to do with
// invalid data. Parse functions throw - they guarantee a valid result or nothing.
// - Use guards when partial success is acceptable (filtering array of mixed data)
// - Use parse functions when invalid data is a programming error that should fail
// ============================================================================

/**
 * EXERCISE 3 PART A: Type Guard for Student
 *
 * Purpose: Safely narrow unknown data to Student type
 * Return Type: value is Student (type predicate)
 * Returns: true if value has Student shape, false otherwise
 *
 * What is a Type Predicate (value is Student)?
 * A return type that tells TypeScript: "If this function returns true,
 * the parameter is guaranteed to be a Student". This enables TYPE NARROWING:
 *
 *   function processStudent(raw: unknown) {
 *     if (isStudent(raw)) {
 *       // Inside this block, TypeScript knows raw is Student
 *       // Autocomplete and type checking work on raw.gpa, raw.name, etc.
 *       console.log(raw.name); // OK: TypeScript knows name exists
 *     }
 *   }
 *
 * Why not just return boolean?
 * function isStudent(value: unknown): boolean {
 *   // ...
 * }
 * // With this signature, the caller still has to cast:
 * // const student = raw as Student; // Unsafe!
 *
 * Type predicate enables safe narrowing without casts.
 *
 * Validation Rules:
 * 1. Input must be an object (not null, not undefined, not primitive)
 * 2. Must have "id" property of type string
 * 3. Must have "name" property of type string
 * 4. Must have "enrollmentDate" property (any Temporal-like value)
 * 5. gpa (if present) must be a number between 0 and 4
 *
 * Returns:
 * - true: If data matches Student shape - safe to use as Student
 * - false: If data doesn't match - caller decides what to do
 *
 * Example Usage:
 *   const raw: unknown = await fetch("/api/students/1").then(r => r.json());
 *   if (isStudent(raw)) {
 *     console.log(`Student ${raw.name} enrolled on ${raw.enrollmentDate}`);
 *   } else {
 *     console.error("API returned invalid student data");
 *   }
 */
export function isStudent(value: unknown): value is Student {
  // Step 1: Check if value is an object type
  // Without this check, "id" in 42 throws a TypeError at runtime
  if (typeof value !== "object" || value === null) {
    return false;
  }

  // Step 2: Check if required string properties exist and have correct type
  // Cast to Record<string, unknown> to safely access dynamic properties
  const obj = value as Record<string, unknown>;

  // Step 3: Validate id field
  if (typeof obj.id !== "string") {
    return false;
  }

  // Step 4: Validate name field
  if (typeof obj.name !== "string") {
    return false;
  }

  // Step 5: Validate enrollmentDate exists
  // (We trust Temporal.Instant if it came from the backend)
  if (!("enrollmentDate" in obj)) {
    return false;
  }

  // Step 6: All validations passed - value is Student
  return true;
}

/**
 * EXERCISE 3 PART B: Parse Function with Detailed Error Messages
 *
 * Purpose: Safely parse unknown data to Student type, throwing on failure
 * Return Type: Student (typed object, never null/undefined)
 * Throws: TypeError with descriptive message if validation fails
 *
 * When to Use:
 * - API data mismatch is a programming error, not a recoverable condition
 * - Throwing forces developers to handle the error immediately
 * - The descriptive message makes debugging real API mismatches straightforward
 *
 * Example Usage:
 *   try {
 *     const student = parseStudent(apiResponse);
 *     console.log(`Enrolled: ${student.name}`);
 *   } catch (error) {
 *     console.error(`Invalid student data: ${error.message}`);
 *     // Log error, alert user, retry with fallback, etc.
 *   }
 *
 * Validation Rules (Same as isStudent):
 * 1. Input must be a non-null object
 * 2. id must be a string
 * 3. name must be a string
 * 4. enrollmentDate must exist
 * 5. gpa (if present) must be a number 0-4
 *
 * Throws: TypeError with field name and actual type received
 * Example: "Expected id to be a string, received number"
 */
export function parseStudent(raw: unknown): Student {
  // Step 1: Validate input is an object
  if (typeof raw !== "object" || raw === null) {
    throw new TypeError(
      `Expected an object, received ${raw === null ? "null" : typeof raw}`
    );
  }

  // Step 2: Cast to Record for safe property access
  const obj = raw as Record<string, unknown>;

  // Step 3: Validate id field
  if (typeof obj.id !== "string") {
    throw new TypeError(
      `Expected id to be a string, received ${typeof obj.id}`
    );
  }

  // Step 4: Validate name field
  if (typeof obj.name !== "string") {
    throw new TypeError(
      `Expected name to be a string, received ${typeof obj.name}`
    );
  }

  // Step 5: Validate enrollmentDate field
  if (!("enrollmentDate" in obj)) {
    throw new TypeError(
      "Expected enrollmentDate field, but it was missing"
    );
  }

  // Step 6: Validate gpa if present (optional field)
  if (obj.gpa !== undefined && typeof obj.gpa !== "number") {
    throw new TypeError(
      `Expected gpa to be a number or undefined, received ${typeof obj.gpa}`
    );
  }

  if (typeof obj.gpa === "number" && (obj.gpa < 0 || obj.gpa > 4)) {
    throw new TypeError(
      `Expected gpa to be between 0 and 4, received ${obj.gpa}`
    );
  }

  // Step 7: All validations passed - return typed Student
  return {
    id: obj.id,
    name: obj.name,
    enrollmentDate: obj.enrollmentDate as Temporal.Instant,
    gpa: obj.gpa as number | undefined,
  };
}

// ============================================================================
// EXERCISE 3 DEMONSTRATION: What Happens with Invalid Data?
// ============================================================================
//
// Example 1: Valid data
//   parseStudent({ id: "STU-001", name: "Hana", enrollmentDate: {...} })
//   Returns: Student { id: "STU-001", name: "Hana", enrollmentDate: {...} }
//
// Example 2: Invalid id (number instead of string)
//   parseStudent({ id: 12345, name: "Hana", enrollmentDate: {...} })
//   Throws: TypeError("Expected id to be a string, received number")
//
// Example 3: Missing field
//   parseStudent({ name: "Hana", enrollmentDate: {...} })
//   Throws: TypeError("Expected id to be a string, received undefined")
//
// Example 4: Null input
//   parseStudent(null)
//   Throws: TypeError("Expected an object, received null")
//
// Example 5: Invalid GPA (out of range)
//   parseStudent({ id: "STU-001", name: "Hana", gpa: 5.0 })
//   Throws: TypeError("Expected gpa to be between 0 and 4, received 5")
//
// The error messages name the specific field and the actual type received.
// This makes debugging real API mismatches straightforward.
// ============================================================================
